---
deployment:
  tasks:
    - export DEPLOYPATH=/home/earesearch/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp events.html $DEPLOYPATH
    - /bin/cp programs.html $DEPLOYPATH
    - /bin/cp publications.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/admin
    - /bin/cp -R admin $DEPLOYPATH