---
deployment:
  tasks:
    - export DEPLOYPATH=/home/earesearch/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp events.html $DEPLOYPATH
    - /bin/cp programs.html $DEPLOYPATH
    - /bin/cp publications.html $DEPLOYPATH
    - /bin/cp opportunity.php $DEPLOYPATH
    - /bin/cp publication.php $DEPLOYPATH
    - /bin/cp founder-story.php $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp newsletter.php $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/api
    - /bin/cp -R api $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/admin
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
